[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_ADDRESS = "https://api.fantasybaseball.xyz"
  REACT_APP_GOOGLE_CLIENT_ID = "286718780152-q76fp5k4tfc9jgt7ltjafeh0rsq9jeq4.apps.googleusercontent.com"
