export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const FETCH_TODAY_GAME_SCHEDULE = "FETCH_TODAY_GAME_SCHEDULE";
export const FETCH_TODAY_USERS_RANKING = "FETCH_TODAY_USERS_RANKING";
export const FETCH_TODAY_PITCHERS_RANKING = "FETCH_TODAY_PITCHERS_RANKING";
export const FETCH_TODAY_HITTERS_RANKING = "FETCH_TODAY_HITTERS_RANKING";
